const $=s=>document.querySelector(s);let revision=null,schema=[],samples=[];const target=()=>$('#target').value;const api=(path,options={})=>fetch(`${path}${path.includes('?')?'&':'?'}target=${target()}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}).then(async r=>{const b=await r.json();if(!b.ok)throw Error(b.error||`HTTP ${r.status}`);return b.result});
function setConnection(ok,text){const e=$('#connection');e.textContent=text;e.className=`pill ${ok?'good':'bad'}`}
async function status(){try{const s=await api('/api/status');window.runtimeStatus=s;setConnection(true,s.mode);$('#scene').textContent=s.resolved_scene||s.active_scene||'—';$('#prediction').textContent=s.predicted_scene||s.latest_prediction||'—';$('#route').textContent=s.route_reason||s.transition_block_reason||'—';$('#lighting').textContent=s.lighting_state||'—';$('#rms').textContent=s.audio_rms==null?'—':Number(s.audio_rms).toFixed(5);$('#queue').textContent=s.prediction_queue_depth==null?'—':`${s.prediction_queue_depth} (max ${s.prediction_queue_max_seen??'—'})`;if($('#graph-enabled').checked&&s.audio_rms!=null){samples.push({t:Date.now(),v:Math.max(0,Number(s.audio_rms)),scene:s.resolved_scene||''});samples=samples.filter(x=>x.t>Date.now()-60000);draw()}}catch(e){setConnection(false,'Disconnected')}}
function draw(){const c=$('#graph'),d=devicePixelRatio||1,w=c.clientWidth,h=180;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,w,h);x.strokeStyle='#2d3841';for(let i=1;i<4;i++){x.beginPath();x.moveTo(0,i*h/4);x.lineTo(w,i*h/4);x.stroke()}if(samples.length<2)return;const start=Date.now()-60000;x.strokeStyle='#49b6ff';x.lineWidth=2;x.beginPath();samples.forEach((p,i)=>{const px=(p.t-start)/60000*w,py=h-Math.min(1,p.v)*h;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();let last='';x.fillStyle='#98a7b4';x.font='11px system-ui';samples.forEach(p=>{if(p.scene&&p.scene!==last){x.fillText(p.scene,(p.t-start)/60000*w+3,14);last=p.scene}})}
function help(f){let limits=[];if(f.minimum!=null)limits.push(`min ${f.minimum}`);if(f.maximum!=null)limits.push(`max ${f.maximum}`);if(f.recommended_minimum!=null||f.recommended_maximum!=null)limits.push(`recommended ${f.recommended_minimum??'—'}–${f.recommended_maximum??'—'}`);return `${f.help}${limits.length?` (${limits.join(', ')}${f.unit?' '+f.unit:''})`:''}`}
function renderFields(values){const root=$('#fields');root.className='field-grid';root.innerHTML='';schema.forEach(f=>{const row=document.createElement('div');row.className='field';row.title=help(f);const label=document.createElement('label');label.htmlFor=`f-${f.path}`;label.textContent=f.label;const small=document.createElement('small');small.textContent=help(f)+(f.apply_mode==='restart'?' · Restart required':' · Live');small.className=f.apply_mode==='restart'?'restart':'';label.appendChild(small);let input;if(f.kind==='choice'){input=document.createElement('select');f.choices.forEach(v=>input.add(new Option(v,v)))}else{input=document.createElement('input');input.type=f.kind==='boolean'?'checkbox':f.kind==='number'?'number':'text';if(f.minimum!=null)input.min=f.minimum;if(f.maximum!=null)input.max=f.maximum;if(f.kind==='number')input.step='any'}input.id=`f-${f.path}`;input.dataset.path=f.path;if(f.kind==='boolean')input.checked=Boolean(values[f.path]);else input.value=values[f.path]??'';row.append(label,input);root.append(row)})}
async function loadConfig(){try{const [s,c,d]=await Promise.all([api('/api/config/schema'),api('/api/config'),api('/api/dynamic-controls')]);schema=s.fields;revision=c.revision;$('#config-path').textContent=c.path;renderFields(c.values);$('#graph-enabled').checked=c.values['web.graph_enabled']!==false;const sel=$('#dynamic');sel.innerHTML='';Object.keys(d.dynamic_controls).forEach(v=>sel.add(new Option(v,v)));sel.value=d.active}catch(e){$('#apply-result').textContent=e.message;$('#apply-result').className='error'}}
async function applyConfig(ev){ev.preventDefault();const changes={};schema.forEach(f=>{const i=$(`#f-${CSS.escape(f.path)}`);changes[f.path]=f.kind==='boolean'?i.checked:f.kind==='number'?Number(i.value):i.value});try{const r=await api('/api/config/apply',{method:'POST',body:JSON.stringify({expected_revision:revision,changes})});revision=r.revision;const needs=r.restart_required.length>0,launch=window.runtimeStatus?.launch||{};let suffix=needs?` Restart required: ${r.restart_required.join(', ')}`:' Applied live.';if(needs&&launch.restart_capability!=='service'&&launch.restart_command)suffix+=` Relaunch with: ${launch.restart_command}`;$('#apply-result').textContent=`Saved.${suffix}`;$('#apply-result').className='success';$('#restart').hidden=!needs||launch.restart_capability!=='service'}catch(e){$('#apply-result').textContent=e.message;$('#apply-result').className='error'}}
async function restart(){if(!confirm('Restart Oculizer now? Lighting control will reconnect automatically.'))return;try{await api('/api/restart',{method:'POST',body:'{}'});$('#apply-result').textContent='Restarting…';$('#restart').hidden=true;setConnection(false,'Restarting')}catch(e){$('#apply-result').textContent=e.message;$('#apply-result').className='error'}}
async function control(body){try{await api('/api/control',{method:'POST',body:JSON.stringify(body)});await status()}catch(e){setConnection(false,e.message)}}
async function logs(){try{const r=await api('/api/logs');$('#logs').textContent=r.records.join('\n');$('#logs').scrollTop=$('#logs').scrollHeight}catch(e){}}
document.addEventListener('DOMContentLoaded',()=>{$('#config-form').addEventListener('submit',applyConfig);$('#restart').addEventListener('click',restart);$('#target').addEventListener('change',()=>{samples=[];$('#restart').hidden=true;loadConfig();status();logs()});document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',()=>control({command:b.dataset.command})));$('#apply-scene').addEventListener('click',()=>control({command:'scene',scene:$('#manual-scene').value}));$('#apply-dynamic').addEventListener('click',()=>control({command:'dynamic-control',name:$('#dynamic').value}));$('#graph-enabled').addEventListener('change',e=>{if(!e.target.checked){samples=[];draw()}});loadConfig();status();logs();setInterval(status,1000);setInterval(logs,3000)});
