"""Runtime loader for a concert-specific model generated by train_predictor_v6.py."""

from pathlib import Path

from oculizer.scene_predictors.v4.predictor import ScenePredictor as V4ScenePredictor


class ScenePredictor(V4ScenePredictor):
    """Use the faster v4 feature contract with independently trained v6 clustering."""

    MODEL_VERSION = "v6"
    PCA_FILENAME = "pca.pkl"
    KMEANS_FILENAME = "kmeans.pkl"

    def __init__(self, model_dir=None, sr=48000, seed=0):
        # v4 resolves its default relative to the module where the inherited
        # method is defined. Supply v6's directory explicitly so its generic
        # artefact names are never looked up under scene_predictors/v4.
        if model_dir is None:
            model_dir = Path(__file__).parent
        super().__init__(model_dir=model_dir, sr=sr, seed=seed)
